(() => {
  'use strict';

  const TOKEN_KEY='gostop-auth-token';
  const baseUrl=String(globalThis.GOSTOP_CONFIG?.serverUrl||'').replace(/\/$/,'');
  let authToken=null,account=null,leaderboardData=null,lobbySocket=null,leaderboardPage=0,leaderboardTimer=null,attractTimer=null,attractMode=false,currentSnapshot=null;
  let pendingChallengeCreate=null,pendingRequest=null,lastAlertKey='',statusTimer=null;
  const $=id=>document.getElementById(id);
  const RANKED_TEXT=Object.freeze({
    en:{coins:'Coins',practice:'Practice Game',coinGames:'COIN GAMES',solo:'Solo Play',online:'Online Play',global:'Global Leaderboard',monthly:'Monthly Leaderboard',pitch:'Create an ID to play games with your friends and compete in the leaderboard.',createId:'Create ID',login:'Log In',logout:'Log Out',rank:'Rank #{rank}',provisional:'Provisional #{rank}',unranked:'Unranked',score:'Score',games:'Games',totalCoins:'Total Coins',gamesPlayed:'Games Played',return:'Return',computer:'Computer #{level}',starting:'Starting Solo Play…',pause:'Pause',pauseCount:'Pause ({count})'},
    ko:{coins:'코인',practice:'연습 게임',coinGames:'코인 게임',solo:'혼자 하기',online:'온라인 플레이',global:'글로벌 리더보드',monthly:'월간 리더보드',pitch:'ID를 만들면 친구와 게임하고 리더보드에서 경쟁할 수 있습니다.',createId:'ID 만들기',login:'로그인',logout:'로그아웃',rank:'순위 #{rank}',provisional:'임시 순위 #{rank}',unranked:'미순위',score:'점수',games:'게임',totalCoins:'총 획득 코인',gamesPlayed:'게임 수',return:'돌아가기',computer:'컴퓨터 #{level}',starting:'혼자 하기 시작 중…',pause:'일시정지',pauseCount:'일시정지 ({count})'},
    es:{coins:'Monedas',practice:'Partida de práctica',coinGames:'PARTIDAS CON MONEDAS',solo:'Juego en solitario',online:'Juego en línea',global:'Clasificación global',monthly:'Clasificación mensual',pitch:'Crea un ID para jugar con amigos y competir en la clasificación.',createId:'Crear ID',login:'Iniciar sesión',logout:'Cerrar sesión',rank:'Puesto #{rank}',provisional:'Provisional #{rank}',unranked:'Sin clasificación',score:'Puntuación',games:'Partidas',totalCoins:'Monedas ganadas',gamesPlayed:'Partidas jugadas',return:'Volver',computer:'Computadora #{level}',starting:'Iniciando juego en solitario…',pause:'Pausa',pauseCount:'Pausa ({count})'},
    fr:{coins:'Pièces',practice:'Partie d’entraînement',coinGames:'PARTIES À PIÈCES',solo:'Jeu solo',online:'Jeu en ligne',global:'Classement mondial',monthly:'Classement mensuel',pitch:'Créez un identifiant pour jouer avec vos amis et concourir au classement.',createId:'Créer un ID',login:'Connexion',logout:'Déconnexion',rank:'Rang #{rank}',provisional:'Provisoire #{rank}',unranked:'Non classé',score:'Score',games:'Parties',totalCoins:'Pièces gagnées',gamesPlayed:'Parties jouées',return:'Retour',computer:'Ordinateur #{level}',starting:'Démarrage du jeu solo…',pause:'Pause',pauseCount:'Pause ({count})'},
    de:{coins:'Münzen',practice:'Übungsspiel',coinGames:'MÜNZSPIELE',solo:'Solo-Spiel',online:'Online-Spiel',global:'Globale Rangliste',monthly:'Monatsrangliste',pitch:'Erstelle eine ID, um mit Freunden zu spielen und in der Rangliste anzutreten.',createId:'ID erstellen',login:'Anmelden',logout:'Abmelden',rank:'Rang #{rank}',provisional:'Vorläufig #{rank}',unranked:'Nicht gewertet',score:'Punkte',games:'Spiele',totalCoins:'Gewonnene Münzen',gamesPlayed:'Gespielte Spiele',return:'Zurück',computer:'Computer #{level}',starting:'Solo-Spiel wird gestartet…',pause:'Pause',pauseCount:'Pause ({count})'},
    ja:{coins:'コイン',practice:'練習ゲーム',coinGames:'コインゲーム',solo:'ソロプレイ',online:'オンラインプレイ',global:'グローバルランキング',monthly:'月間ランキング',pitch:'IDを作成すると友達と対戦し、ランキングに参加できます。',createId:'ID作成',login:'ログイン',logout:'ログアウト',rank:'順位 #{rank}',provisional:'暫定 #{rank}',unranked:'未順位',score:'スコア',games:'ゲーム',totalCoins:'獲得コイン',gamesPlayed:'プレイ数',return:'戻る',computer:'コンピューター #{level}',starting:'ソロプレイ開始中…',pause:'一時停止',pauseCount:'一時停止 ({count})'},
    zh:{coins:'金币',practice:'练习游戏',coinGames:'金币游戏',solo:'单人游戏',online:'在线游戏',global:'全球排行榜',monthly:'月度排行榜',pitch:'创建ID即可与朋友对战并参加排行榜。',createId:'创建ID',login:'登录',logout:'退出登录',rank:'排名 #{rank}',provisional:'暂定 #{rank}',unranked:'未排名',score:'得分',games:'游戏',totalCoins:'赢得金币',gamesPlayed:'游戏局数',return:'返回',computer:'电脑 #{level}',starting:'正在开始单人游戏…',pause:'暂停',pauseCount:'暂停 ({count})'}
  });
  const rankedLocale=()=>Object.hasOwn(RANKED_TEXT,document.documentElement.lang)?document.documentElement.lang:'en';
  const rt=(key,vars={})=>{const locale=rankedLocale(),base=globalThis.GoStopI18n?.dictionaries?.[locale]?.[key],template=RANKED_TEXT[locale]?.[key]??base??RANKED_TEXT.en[key]??key;return String(template).replace(/\{(\w+)\}/g,(_,name)=>vars[name]??'');};
  const coinText=value=>`${Number(value)||0} ${rt('coins')}`;
  try{authToken=localStorage.getItem(TOKEN_KEY)||null;}catch(_){ }
  const apiUrl=path=>`${baseUrl}${path}`;
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[char]));
  const fmtScore=value=>Number(value||0).toFixed(2).replace(/\.00$/,'');
  const flagEmoji=country=>{const code=String(country||'').toUpperCase();return /^[A-Z]{2}$/.test(code)?String.fromCodePoint(...[...code].map(char=>127397+char.charCodeAt(0))):'🌐';};

  async function api(path,{method='GET',body,auth=true}={}){
    if(!baseUrl)throw new Error('Ranked play is unavailable because the server URL is not configured.');
    const headers={};if(body!==undefined)headers['content-type']='application/json';if(auth&&authToken)headers.authorization=`Bearer ${authToken}`;
    const response=await fetch(apiUrl(path),{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),data=await response.json().catch(()=>({}));
    if(!response.ok)throw Object.assign(new Error(data.error?.message||'Request failed.'),data.error||{status:response.status});return data;
  }
  function getAuthToken(){return authToken;}
  function getAccount(){return account?{...account}:null;}
  function rowFor(nickname,page='global'){return (leaderboardData?.[page]||[]).find(row=>String(row.nickname).toLowerCase()===String(nickname||'').toLowerCase())||null;}
  function rankLabel(nickname){const row=rowFor(nickname);if(!row)return rt('unranked');return row.provisional?rt('provisional',{rank:row.rank}):rt('rank',{rank:row.rank});}
  async function refreshLeaderboardData(render=false){try{leaderboardData=await api('/api/leaderboards',{auth:false});if(render)renderAccountBox();return leaderboardData;}catch(_){return leaderboardData;}}
  function saveSession(data){if(data?.session?.token){authToken=data.session.token;try{localStorage.setItem(TOKEN_KEY,authToken);}catch(_){}}if(data?.account)account=data.account;renderAccountBox();refreshLeaderboardData(true);}
  function clearSession(){authToken=null;account=null;leaderboardData=null;try{localStorage.removeItem(TOKEN_KEY);}catch(_){}closeLobby();renderAccountBox();patchGameIdentity();}
  async function refreshAccount(){if(!authToken){renderAccountBox();return null;}try{const data=await api('/api/me');account=data.account;renderAccountBox();await refreshLeaderboardData(true);return account;}catch(_){clearSession();return null;}}
  function updateFromSnapshot(snapshot){if(!snapshot?.youProfile||!account)return;const wallet=Number(snapshot.youProfile.walletCoins);if(Number.isFinite(wallet))account={...account,walletCoins:wallet};renderAccountBox();}

  const style=document.createElement('style');style.textContent=`
    .solo-start-overlay{overflow:auto!important;padding:clamp(22px,4vw,48px)!important;align-content:center}
    .gostop-main-menu{width:min(520px,92vw);display:grid;gap:12px;margin:22px auto 0;position:relative;z-index:2}.gostop-main-menu>button,.ranked-menu-group>button{width:100%;min-height:52px;font-weight:800;font-size:clamp(17px,2.5vw,23px);border-radius:13px}.ranked-menu-group{display:grid;gap:9px;padding:12px;border:2px solid #d7ad68;border-radius:17px;background:linear-gradient(180deg,rgba(215,173,104,.16),rgba(82,50,24,.14));box-shadow:0 0 24px rgba(215,173,104,.12)}.ranked-menu-group:before{content:attr(data-label);font:700 10px/1 system-ui,sans-serif;letter-spacing:2px;color:#f2ce8b;text-align:center}.menu-secondary{background:rgba(28,19,14,.86);border:1px solid rgba(215,173,104,.36);color:#f5e7cc;cursor:pointer}.menu-ranked{background:linear-gradient(180deg,#b98a38,#80551e);border:1px solid #f0cc7b;color:#fff7df;cursor:pointer;box-shadow:inset 0 1px rgba(255,255,255,.22),0 8px 20px rgba(0,0,0,.28)}
    .account-menu-box{position:absolute;right:clamp(12px,3vw,32px);top:clamp(12px,3vw,28px);width:min(300px,42vw);padding:12px 14px;border:1px solid rgba(215,173,104,.52);border-radius:13px;background:rgba(18,12,8,.91);box-shadow:0 10px 28px rgba(0,0,0,.35);z-index:4;font-family:system-ui,sans-serif;text-align:left}.account-menu-box strong{display:block;font-size:15px;color:#fff}.account-menu-box .wallet{display:block;margin-top:3px;color:#f3cf81;font-weight:800}.account-menu-box .rank{display:block;margin-top:2px;color:#d7c8ac;font-size:12px}.account-menu-box p{font-size:11px;line-height:1.35;margin:0 0 9px;color:#d8c4a2}.account-menu-actions{display:flex;gap:6px;flex-wrap:wrap}.account-menu-actions button{font-size:11px;padding:6px 8px;border-radius:8px;border:1px solid rgba(215,173,104,.4);background:#3b2417;color:#fff;cursor:pointer}
    dialog.gostop-account-dialog::backdrop,dialog.gostop-request-dialog::backdrop,dialog.ranked-flow-dialog::backdrop{background:rgba(0,0,0,.72)}.account-dialog-card{width:min(440px,90vw);display:grid;gap:10px}.account-tabs{display:flex;gap:7px}.account-tabs button{flex:1}.account-form{display:grid;gap:8px}.account-form label{display:grid;gap:4px;font:600 12px/1.2 system-ui,sans-serif;color:#ead4af}.account-form input{width:100%;padding:11px 12px;border-radius:9px;border:1px solid rgba(215,173,104,.42);background:#130d09;color:#fff;font:15px system-ui,sans-serif}.account-error{min-height:18px;color:#ff9a86;font:12px system-ui,sans-serif}.account-help{color:#cbb894;font:11px/1.4 system-ui,sans-serif}
    .leaderboard-screen{position:fixed;inset:0;z-index:1900;background:radial-gradient(circle at 50% 15%,#52321f,#130c08 58%,#080503);display:grid;grid-template-rows:auto 1fr auto;gap:12px;padding:clamp(18px,4vw,42px);color:#f5e7cc}.leaderboard-screen[hidden]{display:none}.leaderboard-title{text-align:center}.leaderboard-title h1{margin:0;font-size:clamp(32px,6vw,64px)}.leaderboard-title p{margin:4px 0 0;color:#d3bb92}.leaderboard-table-wrap{overflow:auto;width:min(1050px,92vw);margin:auto;border:1px solid rgba(215,173,104,.36);border-radius:15px;background:rgba(22,14,9,.78)}.leaderboard-table{width:100%;border-collapse:collapse;font-family:system-ui,sans-serif}.leaderboard-table th,.leaderboard-table td{padding:11px 12px;border-bottom:1px solid rgba(215,173,104,.14);text-align:right;white-space:nowrap}.leaderboard-table th:nth-child(2),.leaderboard-table td:nth-child(2){text-align:left}.leaderboard-table th{position:sticky;top:0;background:#29190f;color:#f3ce89}.leaderboard-provisional{opacity:.68}.leaderboard-nav{position:absolute;top:50%;transform:translateY(-50%);width:48px;height:64px;border:1px solid rgba(215,173,104,.45);border-radius:12px;background:rgba(30,18,11,.75);color:#fff;font-size:30px;cursor:pointer}.leaderboard-prev{left:12px}.leaderboard-next{right:12px}.leaderboard-return{justify-self:center;min-width:180px;padding:11px 22px;border-radius:11px;border:1px solid #d7ad68;background:#43281a;color:#fff;font-weight:800;cursor:pointer}.leaderboard-attract-note{text-align:center;font:11px system-ui,sans-serif;color:#9f8a6b}
    .online-lobby-panel{position:fixed;inset:0;z-index:1850;background:rgba(10,7,5,.93);display:grid;place-items:center;padding:18px;overflow:auto}.online-lobby-panel[hidden]{display:none}.online-lobby-card{width:min(760px,94vw);max-height:92vh;overflow:auto;background:#1d130d;border:1px solid rgba(215,173,104,.4);border-radius:17px;padding:20px;box-shadow:0 22px 60px rgba(0,0,0,.55)}.online-lobby-card h2{margin-top:0}.online-method{padding:14px 0;border-top:1px solid rgba(215,173,104,.18)}.online-method:first-of-type{border-top:0}.online-search-row{display:flex;gap:7px}.online-search-row input{flex:1;min-width:0;padding:10px;border-radius:9px;border:1px solid rgba(215,173,104,.35);background:#0e0907;color:#fff}.online-search-row button,.online-lobby-actions button,.online-player-row{border:1px solid rgba(215,173,104,.38);background:#3b2417;color:#fff;border-radius:9px;padding:9px 11px;cursor:pointer}.online-player-list{display:grid;gap:7px;margin-top:9px}.online-player-row{display:grid;grid-template-columns:minmax(130px,1fr) repeat(3,auto);gap:12px;align-items:center;text-align:left}.online-player-row small{color:#bda782}.online-player-row strong{overflow:hidden;text-overflow:ellipsis}.online-lobby-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.online-existing-controls{display:grid;gap:9px}.online-existing-controls .online-join-form{display:grid!important}.lobby-status{min-height:18px;font:12px system-ui,sans-serif;color:#d9c49f}
    .ranked-wallet-line{display:block!important;color:#f0c96f!important;font-weight:700!important;font-size:11px!important}.ranked-pause-btn{border-color:#d7ad68!important}.ranked-flow-dialog .dialog-card{width:min(450px,90vw);text-align:center}.ranked-countdown{display:block;font:800 clamp(32px,8vw,58px)/1 system-ui,sans-serif;color:#f3ce83;margin:14px 0}.ranked-status-toast{position:fixed;left:50%;bottom:22px;transform:translateX(-50%);z-index:2100;background:rgba(19,12,8,.96);border:1px solid #d7ad68;border-radius:11px;padding:10px 16px;font:700 13px system-ui,sans-serif;color:#fff;box-shadow:0 12px 30px rgba(0,0,0,.5)}
    @media(max-width:700px){.account-menu-box{position:relative;right:auto;top:auto;width:min(520px,92vw);margin:10px auto 0}.solo-start-overlay{align-content:start!important}.gostop-main-menu{margin-top:12px}.online-player-row{grid-template-columns:1fr 1fr;gap:5px}.leaderboard-nav{width:38px;height:54px}.leaderboard-table th,.leaderboard-table td{padding:9px 7px;font-size:12px}}
  `;document.head.appendChild(style);

  const overlay=$('soloStartOverlay'),playPractice=$('playSoloBtn'),createRoom=$('createOnlineBtn'),joinForm=$('joinOnlineForm'),howTo=$('howToBtn'),onlineStatus=$('onlineStatus');if(!overlay||!playPractice)return;
  playPractice.textContent='Practice Game';playPractice.className='menu-secondary';
  const accountBox=document.createElement('aside');accountBox.id='accountMenuBox';accountBox.className='account-menu-box';overlay.appendChild(accountBox);
  const menu=document.createElement('div');menu.className='gostop-main-menu';const rankedGroup=document.createElement('div');rankedGroup.className='ranked-menu-group';
  const rankedSolo=document.createElement('button');rankedSolo.type='button';rankedSolo.className='menu-ranked';rankedSolo.textContent='Solo Play';rankedSolo.id='rankedSoloBtn';
  const onlinePlay=document.createElement('button');onlinePlay.type='button';onlinePlay.className='menu-ranked';onlinePlay.textContent='Online Play';onlinePlay.id='onlinePlayMenuBtn';
  const leaderboardBtn=document.createElement('button');leaderboardBtn.type='button';leaderboardBtn.className='menu-secondary';leaderboardBtn.textContent='Global Leaderboard';leaderboardBtn.id='leaderboardMenuBtn';if(howTo){howTo.className='menu-secondary';howTo.textContent='How to Play';}
  rankedGroup.append(rankedSolo,onlinePlay);menu.append(playPractice,rankedGroup,leaderboardBtn);if(howTo)menu.append(howTo);overlay.appendChild(menu);

  const onlinePanel=document.createElement('section');onlinePanel.id='onlineLobbyPanel';onlinePanel.className='online-lobby-panel';onlinePanel.hidden=true;onlinePanel.innerHTML=`<div class="online-lobby-card"><h2>Online Play</h2><div class="online-method"><strong>Invite by Email</strong><p class="account-help">Enter a friend's email. Server email delivery will be enabled when the mail provider is connected; room-code sharing remains available now.</p><div class="online-search-row"><input id="onlineInviteEmail" type="email" autocomplete="email" placeholder="friend@example.com"><button id="onlineInviteEmailBtn" type="button">Send Invite</button></div></div><div class="online-method"><strong>Find an Online Player</strong><p class="account-help">Search by nickname or choose one of the five online players closest to you by Score, Games Played, and Wallet Coins.</p><div class="online-search-row"><input id="onlineNicknameSearch" autocomplete="off" placeholder="Nickname"><button id="onlineNicknameSearchBtn" type="button">Search</button></div><div id="recommendedPlayers" class="online-player-list"></div></div><div class="online-method"><strong>Room Code / Share Link</strong><div id="onlineExistingControls" class="online-existing-controls"></div></div><p id="lobbyStatus" class="lobby-status" role="status"></p><div class="online-lobby-actions"><button id="onlineLobbyClose" type="button">Return</button></div></div>`;document.body.appendChild(onlinePanel);
  const controls=$('onlineExistingControls');if(createRoom){createRoom.textContent='Create Room / Share Code';controls.appendChild(createRoom);}if(joinForm)controls.appendChild(joinForm);if(onlineStatus)controls.appendChild(onlineStatus);

  const authDialog=document.createElement('dialog');authDialog.id='accountDialog';authDialog.className='gostop-account-dialog';authDialog.innerHTML=`<div class="dialog-card account-dialog-card"><button class="dialog-close" id="accountDialogClose" type="button" aria-label="Close">×</button><h2>Log In</h2><div class="account-tabs"><button id="loginTab" class="glass-btn strong" type="button">Log In</button><button id="registerTab" class="glass-btn" type="button">Create ID</button></div><form id="loginForm" class="account-form"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="go-btn" type="submit">Log In</button></form><form id="registerForm" class="account-form" hidden><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Nickname<input name="nickname" maxlength="16" required></label><label>Password<input name="password" type="password" autocomplete="new-password" required></label><label>Confirm Password<input name="confirmPassword" type="password" autocomplete="new-password" required></label><p class="account-help">Use at least 8 characters. Common passwords such as 12345 or qwerty are not accepted.</p><button class="go-btn" type="submit">Register</button></form><p id="accountError" class="account-error" role="alert"></p></div>`;document.body.appendChild(authDialog);
  const successDialog=document.createElement('dialog');successDialog.className='gostop-account-dialog';successDialog.innerHTML=`<div class="dialog-card account-dialog-card"><h2>Account Registered Successfully</h2><p>You received 100 signup bonus coins + 100 daily login bonus coins.</p><button id="registrationOk" class="go-btn" type="button">OK</button></div>`;document.body.appendChild(successDialog);
  const requestDialog=document.createElement('dialog');requestDialog.className='gostop-request-dialog';requestDialog.innerHTML=`<div class="dialog-card"><h2>Online Play Request</h2><p id="requestPlayerName"></p><p id="requestPlayerStats" class="account-help"></p><div class="decision-actions"><button id="requestAccept" class="go-btn" type="button">Accept</button><button id="requestDecline" class="stop-btn" type="button">Decline</button></div></div>`;document.body.appendChild(requestDialog);

  const leaderboardScreen=document.createElement('section');leaderboardScreen.className='leaderboard-screen';leaderboardScreen.hidden=true;leaderboardScreen.innerHTML=`<header class="leaderboard-title"><h1 id="leaderboardHeading">Global Leaderboard</h1><p id="leaderboardSubheading"></p></header><button class="leaderboard-nav leaderboard-prev" type="button" aria-label="Previous">‹</button><div class="leaderboard-table-wrap"><table class="leaderboard-table"><thead><tr><th>Rank</th><th>Nickname</th><th>Score</th><th>Total Coins</th><th>Games Played</th></tr></thead><tbody id="leaderboardBody"></tbody></table></div><button class="leaderboard-nav leaderboard-next" type="button" aria-label="Next">›</button><div><p class="leaderboard-attract-note" id="leaderboardAttractNote"></p><button class="leaderboard-return" type="button">Return</button></div>`;document.body.appendChild(leaderboardScreen);

  const pauseDialog=document.createElement('dialog');pauseDialog.className='ranked-flow-dialog';pauseDialog.innerHTML=`<div class="dialog-card"><h2>PAUSE</h2><span id="rankedPauseCountdown" class="ranked-countdown">1:00</span><p id="rankedPauseText"></p><p id="rankedPauseRemaining" class="account-help"></p></div>`;document.body.appendChild(pauseDialog);
  const inactivityDialog=document.createElement('dialog');inactivityDialog.className='ranked-flow-dialog';inactivityDialog.innerHTML=`<div class="dialog-card"><h2 id="rankedInactivityTitle">Your Turn</h2><span id="rankedInactivityCountdown" class="ranked-countdown" hidden></span><p id="rankedInactivityText"></p><button id="rankedInactivityOk" class="go-btn" type="button">OK</button></div>`;document.body.appendChild(inactivityDialog);
  const rankedQuitDialog=document.createElement('dialog');rankedQuitDialog.className='ranked-flow-dialog';rankedQuitDialog.innerHTML=`<div class="dialog-card"><h2 id="rankedQuitTitle">Quit Request</h2><p id="rankedQuitText"></p><div id="rankedQuitActions" class="decision-actions"><button id="rankedQuitAccept" class="go-btn" type="button">Accept</button><button id="rankedQuitDecline" class="stop-btn" type="button">Decline</button></div></div>`;document.body.appendChild(rankedQuitDialog);
  const abandonmentDialog=document.createElement('dialog');abandonmentDialog.className='ranked-flow-dialog';abandonmentDialog.innerHTML=`<div class="dialog-card"><h2>Game Ended</h2><p id="rankedAbandonmentText"></p><button id="rankedAbandonmentOk" class="go-btn" type="button">OK</button></div>`;document.body.appendChild(abandonmentDialog);
  const pauseBtn=document.createElement('button');pauseBtn.id='rankedPauseBtn';pauseBtn.type='button';pauseBtn.className='glass-btn ranked-pause-btn';pauseBtn.textContent='Pause (2)';pauseBtn.hidden=true;document.querySelector('.round-status')?.prepend(pauseBtn);
  const toast=document.createElement('div');toast.className='ranked-status-toast';toast.hidden=true;document.body.appendChild(toast);

  function showToast(text,ms=4000){toast.textContent=text;toast.hidden=false;if(statusTimer)clearTimeout(statusTimer);statusTimer=setTimeout(()=>toast.hidden=true,ms);}
  function applyRankedLocale(){
    playPractice.textContent=rt('practice');rankedGroup.dataset.label=rt('coinGames');rankedSolo.textContent=rankedSolo.disabled?rt('starting'):rt('solo');onlinePlay.textContent=rt('online');leaderboardBtn.textContent=rt('global');if(howTo)howTo.textContent=rt('howTo');
    const lobbyCard=onlinePanel.querySelector('.online-lobby-card'),methods=onlinePanel.querySelectorAll('.online-method');if(lobbyCard?.querySelector('h2'))lobbyCard.querySelector('h2').textContent=rt('online');if(methods[2]?.querySelector('strong'))methods[2].querySelector('strong').textContent=rt('roomCode')+' / '+rt('shareRoomCode',{roomCode:''}).replace(/[:：]\s*$/,'');if(createRoom)createRoom.textContent=rt('createOnlineGame');$('onlineLobbyClose').textContent=rt('return');
    $('loginTab').textContent=rt('login');$('registerTab').textContent=rt('createId');authDialog.querySelector('h2').textContent=$('registerForm').hidden?rt('login'):rt('createId');successDialog.querySelector('h2').textContent=rankedLocale()==='ko'?'계정 등록 완료':successDialog.querySelector('h2').textContent;$('registrationOk').textContent=rt('ok');
    const heads=leaderboardScreen.querySelectorAll('th');if(heads[0])heads[0].textContent=rt('rank',{rank:''}).replace(/\s*#?\s*$/,'');if(heads[1])heads[1].textContent=rt('nickname');if(heads[2])heads[2].textContent=rt('score');if(heads[3])heads[3].textContent=rt('totalCoins');if(heads[4])heads[4].textContent=rt('gamesPlayed');leaderboardScreen.querySelector('.leaderboard-return').textContent=rt('return');pauseDialog.querySelector('h2').textContent=rt('pause');
    renderAccountBox();if(leaderboardData)renderLeaderboard();patchGameIdentity();
  }
  function renderAccountBox(){
    if(!account){accountBox.innerHTML=`<p>${escapeHtml(rt('pitch'))}</p><div class="account-menu-actions"><button id="accountCreateBtn" type="button">${escapeHtml(rt('createId'))}</button><button id="accountLoginBtn" type="button">${escapeHtml(rt('login'))}</button></div>`;$('accountCreateBtn')?.addEventListener('click',()=>openAuth('register'));$('accountLoginBtn')?.addEventListener('click',()=>openAuth('login'));return;}
    accountBox.innerHTML=`<strong>${flagEmoji(account.countryCode)} ${escapeHtml(account.nickname)}</strong><span class="wallet">🪙 ${escapeHtml(coinText(account.walletCoins))}</span><span class="rank">${escapeHtml(rankLabel(account.nickname))}</span><div class="account-menu-actions"><button id="accountLogoutBtn" type="button">${escapeHtml(rt('logout'))}</button></div>`;$('accountLogoutBtn')?.addEventListener('click',logout);
  }
  function openAuth(tab='login'){setAuthTab(tab);$('accountError').textContent='';if(!authDialog.open)authDialog.showModal();}
  function setAuthTab(tab){const login=tab!=='register';$('loginForm').hidden=!login;$('registerForm').hidden=login;$('loginTab').classList.toggle('strong',login);$('registerTab').classList.toggle('strong',!login);}
  async function logout(){try{await api('/api/auth/logout',{method:'POST',body:{}});}catch(_){}clearSession();}
  $('accountDialogClose').addEventListener('click',()=>authDialog.close());$('loginTab').addEventListener('click',()=>setAuthTab('login'));$('registerTab').addEventListener('click',()=>setAuthTab('register'));$('registrationOk').addEventListener('click',()=>successDialog.close());
  $('loginForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);try{$('accountError').textContent='';const data=await api('/api/auth/login',{method:'POST',body:{email:form.get('email'),password:form.get('password')},auth:false});saveSession(data);authDialog.close();}catch(error){$('accountError').textContent=error.message;}});
  $('registerForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget),body={email:form.get('email'),nickname:form.get('nickname'),password:form.get('password'),confirmPassword:form.get('confirmPassword')};if(Object.values(body).some(value=>!String(value||'').trim())){$('accountError').textContent='Please fill out all registration information.';return;}try{$('accountError').textContent='';const data=await api('/api/auth/register',{method:'POST',body,auth:false});saveSession(data);authDialog.close();successDialog.showModal();}catch(error){$('accountError').textContent=error.message;}});

  function requireAccount(next){if(account){next();return;}openAuth('login');const handler=()=>{authDialog.removeEventListener('close',handler);if(account)next();};authDialog.addEventListener('close',handler);}
  rankedSolo.addEventListener('click',()=>requireAccount(async()=>{try{rankedSolo.disabled=true;rankedSolo.textContent=rt('starting');const data=await api('/api/solo',{method:'POST',body:{}}),input=$('onlineRoomCode');if(!input||!joinForm)throw new Error('Online game launcher is unavailable.');input.value=data.room.roomCode;onlinePanel.hidden=true;joinForm.requestSubmit();}catch(error){showToast(error.message,6000);}finally{rankedSolo.disabled=false;rankedSolo.textContent=rt('solo');}}));
  onlinePlay.addEventListener('click',()=>requireAccount(()=>{onlinePanel.hidden=false;connectLobby();requestRecommendations();}));
  $('onlineLobbyClose').addEventListener('click',()=>{onlinePanel.hidden=true;resetAttractTimer();});

  function renderLeaderboard(){if(!leaderboardData)return;const key=leaderboardPage===0?'global':'monthly',rows=leaderboardData[key]||[];$('leaderboardHeading').textContent=leaderboardPage===0?'Global Leaderboard':'Monthly Leaderboard';$('leaderboardSubheading').textContent=leaderboardPage===0?'Overall global leaderboard to date':`${leaderboardData.month||'Current month'} to date`;$('leaderboardBody').innerHTML=rows.map(row=>`<tr class="${row.provisional?'leaderboard-provisional':''}"><td>${row.provisional?'P ':''}${row.rank}</td><td>${flagEmoji(row.countryCode)} ${escapeHtml(row.nickname)}</td><td>${fmtScore(row.score)}</td><td>${Number(row.totalCoins)||0}</td><td>${Number(row.gamesPlayed)||0}</td></tr>`).join('')||'<tr><td colspan="5" style="text-align:center">No ranked games yet.</td></tr>';$('leaderboardAttractNote').textContent=attractMode?'Attract Mode · touch or click anywhere to return to the menu':'Global and Monthly pages rotate every 5 seconds.';}
  function nextLeaderboard(delta=1){leaderboardPage=(leaderboardPage+delta+2)%2;renderLeaderboard();restartLeaderboardTimer();}
  function restartLeaderboardTimer(){if(leaderboardTimer)clearInterval(leaderboardTimer);if(!leaderboardScreen.hidden)leaderboardTimer=setInterval(()=>nextLeaderboard(1),5000);}
  async function openLeaderboard(isAttract=false){await refreshLeaderboardData();attractMode=isAttract;leaderboardPage=0;leaderboardScreen.hidden=false;renderLeaderboard();restartLeaderboardTimer();}
  function closeLeaderboard(){leaderboardScreen.hidden=true;attractMode=false;if(leaderboardTimer)clearInterval(leaderboardTimer);leaderboardTimer=null;resetAttractTimer();}
  leaderboardBtn.addEventListener('click',event=>{event.stopPropagation();openLeaderboard(false);});leaderboardScreen.querySelector('.leaderboard-prev').addEventListener('click',event=>{event.stopPropagation();nextLeaderboard(-1);});leaderboardScreen.querySelector('.leaderboard-next').addEventListener('click',event=>{event.stopPropagation();nextLeaderboard(1);});leaderboardScreen.querySelector('.leaderboard-return').addEventListener('click',event=>{event.stopPropagation();closeLeaderboard();});leaderboardScreen.addEventListener('click',event=>{if(event.target.closest('button'))return;if(attractMode){closeLeaderboard();return;}nextLeaderboard(1);});
  function resetAttractTimer(){if(attractTimer)clearTimeout(attractTimer);if(!overlay.hidden&&leaderboardScreen.hidden&&!onlinePanel.hidden===false)attractTimer=setTimeout(()=>{if(!overlay.hidden&&onlinePanel.hidden)openLeaderboard(true);},10000);}
  document.addEventListener('pointerdown',()=>{if(attractMode){closeLeaderboard();return;}resetAttractTimer();},{capture:true});document.addEventListener('keydown',resetAttractTimer,{capture:true});

  function lobbyUrl(){const url=new URL(`${baseUrl}/api/lobby/ws`);url.protocol=url.protocol==='https:'?'wss:':'ws:';return url;}
  function connectLobby(){if(!authToken||!baseUrl||lobbySocket?.readyState===WebSocket.OPEN)return;try{lobbySocket=new WebSocket(lobbyUrl(),`gostop-auth.${authToken}`);lobbySocket.addEventListener('open',()=>requestRecommendations());lobbySocket.addEventListener('message',event=>handleLobbyMessage(JSON.parse(event.data)));lobbySocket.addEventListener('close',()=>{lobbySocket=null;if(!onlinePanel.hidden)$('lobbyStatus').textContent='Online player list disconnected. Reopen Online Play to reconnect.';});}catch(error){$('lobbyStatus').textContent=error.message;}}
  function closeLobby(){if(lobbySocket){lobbySocket.close();lobbySocket=null;}}
  function lobbySend(message){if(lobbySocket?.readyState!==WebSocket.OPEN)return false;lobbySocket.send(JSON.stringify(message));return true;}
  function requestRecommendations(){if(lobbySocket?.readyState===WebSocket.OPEN)lobbySend({type:'recommendations'});}
  function renderPlayers(players=[]){$('recommendedPlayers').innerHTML=players.length?players.map(player=>`<button type="button" class="online-player-row" data-account-id="${escapeHtml(player.accountId)}"><strong>${flagEmoji(player.countryCode)} ${escapeHtml(player.nickname)}${player.rank?` · #${player.rank}`:''}</strong><small>${escapeHtml(rt('score'))} ${fmtScore(player.score)}</small><small>${Number(player.gamesPlayed)||0} ${escapeHtml(rt('games'))}</small><small>🪙 ${escapeHtml(coinText(player.walletCoins))}</small></button>`).join(''):'<p class="account-help">No matching available players are online right now.</p>';for(const button of $('recommendedPlayers').querySelectorAll('[data-account-id]'))button.addEventListener('click',()=>{if(lobbySend({type:'challenge',accountId:button.dataset.accountId}))$('lobbyStatus').textContent='Play request sent…';});}
  function handleLobbyMessage(message){
    if(message.type==='connected'){if(message.account){account={...account,...message.account};renderAccountBox();}return;}
    if(message.type==='recommendations'||message.type==='searchResults'){renderPlayers(message.players||[]);return;}
    if(message.type==='challengeSent'){$('lobbyStatus').textContent=`Waiting for ${message.to?.nickname||'player'} to respond…`;return;}
    if(message.type==='playRequest'){pendingRequest=message;const from=message.from||{};$('requestPlayerName').textContent=`${flagEmoji(from.countryCode)} ${from.nickname||'Player'} wants to play GoStop with you.`;$('requestPlayerStats').textContent=`${from.rank?`Rank #${from.rank} · `:''}Score ${fmtScore(from.score)} · ${from.gamesPlayed||0} games · ${from.walletCoins||0} Coins`;if(!requestDialog.open)requestDialog.showModal();return;}
    if(message.type==='challengeAcceptedCreateRoom'){pendingChallengeCreate=message.requestId;$('lobbyStatus').textContent='Accepted — creating the game room…';onlinePanel.hidden=true;createRoom?.click();return;}
    if(message.type==='challengeAcceptedWaiting'){$('lobbyStatus').textContent='Accepted — waiting for the other player to create the room…';return;}
    if(message.type==='challengeRoomReady'){const input=$('onlineRoomCode');if(!input||!joinForm)return;input.value=message.roomCode;onlinePanel.hidden=true;joinForm.requestSubmit();return;}
    if(message.type==='challengeRoomHandoffComplete'){pendingChallengeCreate=null;onlinePanel.hidden=true;return;}
    if(message.type==='challengeDeclined'){$('lobbyStatus').textContent=`${message.by?.nickname||'Player'} declined the request.`;requestRecommendations();return;}
    if(message.type==='challengeCancelled'||message.type==='challengeError'){pendingChallengeCreate=null;$('lobbyStatus').textContent=message.message||'The play request could not be completed.';requestRecommendations();return;}
  }
  $('requestAccept').addEventListener('click',()=>{if(pendingRequest)lobbySend({type:'challengeResponse',requestId:pendingRequest.requestId,accept:true});pendingRequest=null;requestDialog.close();});$('requestDecline').addEventListener('click',()=>{if(pendingRequest)lobbySend({type:'challengeResponse',requestId:pendingRequest.requestId,accept:false});pendingRequest=null;requestDialog.close();});
  $('onlineNicknameSearchBtn').addEventListener('click',()=>{const query=$('onlineNicknameSearch').value.trim();lobbySend(query?{type:'search',query}:{type:'recommendations'});});$('onlineNicknameSearch').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();$('onlineNicknameSearchBtn').click();}});
  $('onlineInviteEmailBtn').addEventListener('click',()=>{const email=$('onlineInviteEmail').value.trim();$('lobbyStatus').textContent=email?'Email delivery needs the outbound mail provider. For now, use Create Room / Share Code below.':'Enter an email address first.';});
  globalThis.addEventListener('gostop-online-room-created',event=>{if(!pendingChallengeCreate)return;const roomCode=event.detail?.room?.roomCode;if(roomCode&&lobbySend({type:'challengeRoomReady',requestId:pendingChallengeCreate,roomCode}))$('lobbyStatus').textContent='Room created. The other player is joining…';});

  function gameRow(nickname){return rowFor(nickname,'global');}
  function ensureWalletLine(root,id){let line=root?.querySelector(`.${id}`);if(!line&&root){line=document.createElement('span');line.className=`ranked-wallet-line ${id}`;root.appendChild(line);}return line;}
  function patchGameIdentity(){
    const humanIdentity=document.querySelector('.human-chip .player-identity'),opponentIdentity=document.querySelector('.cpu-chip .player-identity'),humanName=humanIdentity?.querySelector('strong'),opponentName=opponentIdentity?.querySelector('strong');if(!humanName||!opponentName)return;
    const rankedMode=currentSnapshot?.sessionFlow?.rankedMode;
    if(account){const rank=rankLabel(account.nickname);humanName.textContent=`${rt('you')} (${account.nickname}) · ${rank}`;const line=ensureWalletLine(humanIdentity,'ranked-human-wallet');if(line)line.textContent=`🪙 ${coinText(account.walletCoins)}`;}
    else {humanName.textContent='You';humanIdentity?.querySelector('.ranked-human-wallet')?.remove();}
    if(currentSnapshot?.ranked&&currentSnapshot.opponentProfile){const opponent=currentSnapshot.opponentProfile;if(rankedMode==='solo'||opponent.bot){opponentName.textContent=rt('computer',{level:opponent.computerLevel||1});}else{const row=gameRow(opponent.nickname),rank=row?(row.provisional?`Provisional #${row.rank}`:`Rank #${row.rank}`):'Unranked';opponentName.textContent=`${opponent.nickname||'Opponent'} · ${rank}`;}const line=ensureWalletLine(opponentIdentity,'ranked-opponent-wallet');if(line)line.textContent=`🪙 ${coinText(opponent.walletCoins)}`;}else if(!currentSnapshot){opponentIdentity?.querySelector('.ranked-opponent-wallet')?.remove();}
  }
  playPractice.addEventListener('click',()=>setTimeout(patchGameIdentity,0),{capture:true});

  function submitRanked(action){try{return globalThis.goStopOnlineSession?.submit(action)||null;}catch(error){showToast(error.message,5000);return null;}}
  function alertPlayer(key){if(lastAlertKey===key)return;lastAlertKey=key;try{navigator.vibrate?.([120,70,120]);const Context=globalThis.AudioContext||globalThis.webkitAudioContext;if(Context){const ctx=new Context(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=880;gain.gain.value=.05;osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.14);osc.onended=()=>ctx.close();}}catch(_){}}
  let flowInterval=null;
  function startFlowClock(){if(flowInterval)return;flowInterval=setInterval(()=>renderRankedFlow(currentSnapshot),250);}
  function stopFlowClockIfIdle(){const flow=currentSnapshot?.sessionFlow;if(flow?.pause||flow?.inactivity?.phase==='warning')return;if(flowInterval){clearInterval(flowInterval);flowInterval=null;}}
  function setDialog(dialog,open){if(open&&!dialog.open)dialog.showModal();else if(!open&&dialog.open)dialog.close();}
  function renderRankedFlow(snapshot){
    const flow=snapshot?.sessionFlow;if(!flow){pauseBtn.hidden=true;setDialog(pauseDialog,false);setDialog(inactivityDialog,false);setDialog(rankedQuitDialog,false);return;}
    const onlineRanked=snapshot.ranked&&flow.rankedMode==='online'&&!flow.ended;pauseBtn.hidden=!onlineRanked;const remaining=flow.pausesRemaining?.you??flow.pause?.remainingForYou??2;pauseBtn.textContent=rt('pauseCount',{count:remaining});pauseBtn.disabled=!onlineRanked||remaining<=0||!!flow.pause||!!snapshot.terminalResult;
    if(flow.pause){const seconds=Math.max(0,Math.ceil((flow.pause.until-Date.now())/1000));$('rankedPauseCountdown').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('rankedPauseText').textContent=flow.pause.requestedByYou?'You requested a one-minute pause.':'Your opponent requested a one-minute pause.';$('rankedPauseRemaining').textContent=`Your pauses remaining this game: ${flow.pause.remainingForYou}`;setDialog(pauseDialog,true);startFlowClock();}else setDialog(pauseDialog,false);
    const inactivity=flow.inactivity;if(!inactivity||inactivity.phase==='waiting'){setDialog(inactivityDialog,false);if(!flow.pause)stopFlowClockIfIdle();}else if(inactivity.phase==='nudge'){const own=inactivity.byYou;$('rankedInactivityTitle').textContent=own?'YOUR TURN!':'Waiting for Opponent';$('rankedInactivityCountdown').hidden=true;$('rankedInactivityText').textContent=own?'Please play your turn. If you remain inactive, an abandonment warning will follow.':'Your opponent has been nudged to play.';$('rankedInactivityOk').textContent=own?'Play Now':'OK';setDialog(inactivityDialog,true);if(own)alertPlayer(`nudge:${snapshot.matchId}:${inactivity.nudgeAt}`);}else if(inactivity.phase==='warning'){const own=inactivity.byYou,seconds=Math.max(0,Math.ceil((inactivity.abandonAt-Date.now())/1000));$('rankedInactivityTitle').textContent='30-SECOND ABANDONMENT WARNING';$('rankedInactivityCountdown').hidden=false;$('rankedInactivityCountdown').textContent=String(seconds);$('rankedInactivityText').textContent=own?`Play now or the game will end and a ${inactivity.penaltyCoins||0}-Coin penalty will apply.`:`Opponent has ${seconds} seconds to play before an abandonment penalty is applied.`;$('rankedInactivityOk').textContent=own?'Play Now':'OK';setDialog(inactivityDialog,true);startFlowClock();if(own)alertPlayer(`warning:${snapshot.matchId}:${inactivity.warningAt}`);}
    const quit=flow.quitRequest;if(quit){$('rankedQuitTitle').textContent=quit.requestedByYou?'Waiting for Opponent':'Opponent Wants to Quit';$('rankedQuitText').textContent=quit.requestedByYou?'Waiting for your opponent to agree to end the session. If declined, you will leave after the current game.':'Your opponent requested to end the session now. Do you agree?';$('rankedQuitActions').hidden=quit.requestedByYou;setDialog(rankedQuitDialog,true);}else setDialog(rankedQuitDialog,false);
    if(flow.scheduledQuitByYou)showToast('Quit scheduled: this session will end after the current game.',5000);
    if(flow.abandonment){$('rankedAbandonmentText').textContent=flow.abandonment.byYou?`The game ended due to abandonment. ${flow.abandonment.penaltyCoins} Coins were deducted from your Wallet.`:`Your opponent abandoned the game. You receive ${flow.abandonment.penaltyCoins} Coins.`;setDialog(abandonmentDialog,true);}
  }
  pauseBtn.addEventListener('click',()=>submitRanked({type:'requestPause'}));$('rankedInactivityOk').addEventListener('click',()=>inactivityDialog.close());$('rankedQuitAccept').addEventListener('click',()=>{const id=currentSnapshot?.sessionFlow?.quitRequest?.requestId;if(id)submitRanked({type:'respondQuit',requestId:id,accept:true});});$('rankedQuitDecline').addEventListener('click',()=>{const id=currentSnapshot?.sessionFlow?.quitRequest?.requestId;if(id)submitRanked({type:'respondQuit',requestId:id,accept:false});});$('rankedAbandonmentOk').addEventListener('click',()=>abandonmentDialog.close());[pauseDialog,rankedQuitDialog].forEach(dialog=>dialog.addEventListener('cancel',event=>event.preventDefault()));

  globalThis.addEventListener('gostop-online-snapshot',event=>{const snapshot=event.detail?.snapshot;if(!snapshot)return;const terminalChanged=!!snapshot.terminalResult&&!currentSnapshot?.terminalResult;currentSnapshot=snapshot;updateFromSnapshot(snapshot);renderRankedFlow(snapshot);patchGameIdentity();setTimeout(patchGameIdentity,0);if(terminalChanged){refreshLeaderboardData(true).then(()=>patchGameIdentity());refreshAccount();}});
  globalThis.addEventListener('gostop-online-message',event=>{const message=event.detail||{};if(message.type==='opponentDisconnected')showToast('Opponent disconnected. Waiting up to 45 seconds for reconnection.',7000);else if(message.type==='opponentConnected')showToast('Opponent reconnected.',3000);});

  const roomParam=new URL(location.href).searchParams.get('room');if(roomParam&&/^[A-Z2-9]{14}$/i.test(roomParam)){const launch=()=>{const input=$('onlineRoomCode');if(input&&joinForm){input.value=roomParam.toUpperCase();joinForm.requestSubmit();}};if(account)setTimeout(launch,0);else setTimeout(()=>requireAccount(launch),0);}

  globalThis.GoStopRanked=Object.freeze({getAuthToken,getAccount,refreshAccount,refreshLeaderboardData,updateFromSnapshot,openLeaderboard,patchGameIdentity});
  new MutationObserver(records=>{if(records.some(record=>record.attributeName==='lang'))applyRankedLocale();}).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
  applyRankedLocale();refreshAccount().finally(()=>{applyRankedLocale();resetAttractTimer();});
})();
