(() => {
  'use strict';

  const TOKEN_KEY='gostop-auth-token';
  const baseUrl=String(globalThis.GOSTOP_CONFIG?.serverUrl||'').replace(/\/$/,'');
  let authToken=null,account=null,lobbySocket=null,leaderboardData=null,leaderboardPage=0,leaderboardTimer=null,attractTimer=null,attractMode=false;
  const authWaiters=[];
  try{authToken=localStorage.getItem(TOKEN_KEY)||null;}catch(_){ }

  const $=id=>document.getElementById(id);
  const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const flagEmoji=country=>{const code=String(country||'').toUpperCase();return /^[A-Z]{2}$/.test(code)?String.fromCodePoint(...[...code].map(char=>127397+char.charCodeAt(0))):'🌐';};
  const fmtScore=value=>Number(value||0).toFixed(2).replace(/\.00$/,'');
  const apiUrl=path=>`${baseUrl}${path}`;
  async function api(path,{method='GET',body,auth=true}={}){
    const headers={};if(body!==undefined)headers['content-type']='application/json';if(auth&&authToken)headers.authorization=`Bearer ${authToken}`;
    const response=await fetch(apiUrl(path),{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),data=await response.json().catch(()=>({}));
    if(!response.ok)throw Object.assign(new Error(data.error?.message||'Request failed.'),data.error||{status:response.status});
    return data;
  }
  function saveSession(data){
    if(data?.session?.token){authToken=data.session.token;try{localStorage.setItem(TOKEN_KEY,authToken);}catch(_){}}
    if(data?.account)account=data.account;renderAccountBox();resolveAuthWaiters();
  }
  function clearSession(){authToken=null;account=null;try{localStorage.removeItem(TOKEN_KEY);}catch(_){};closeLobby();renderAccountBox();}
  function getAuthToken(){return authToken;}
  function getAccount(){return account?{...account}:null;}
  function resolveAuthWaiters(){while(authWaiters.length)authWaiters.shift()?.(account);}
  async function refreshAccount(){if(!authToken){renderAccountBox();return null;}try{const data=await api('/api/me');account=data.account;renderAccountBox();return account;}catch(_){clearSession();return null;}}
  function updateFromSnapshot(snapshot){if(!snapshot?.youProfile||!account)return;const wallet=Number(snapshot.youProfile.walletCoins);if(Number.isFinite(wallet))account={...account,walletCoins:wallet};renderAccountBox();}

  const style=document.createElement('style');style.textContent=`
    .solo-start-overlay{overflow:auto!important;padding:clamp(22px,4vw,48px)!important;align-content:center}
    .gostop-main-menu{width:min(520px,92vw);display:grid;gap:12px;margin:22px auto 0;position:relative;z-index:2}
    .gostop-main-menu>button,.gostop-main-menu .ranked-menu-group>button{width:100%;min-height:52px;font-weight:800;font-size:clamp(17px,2.5vw,23px);border-radius:13px}
    .ranked-menu-group{display:grid;gap:9px;padding:12px;border:2px solid #d7ad68;border-radius:17px;background:linear-gradient(180deg,rgba(215,173,104,.16),rgba(82,50,24,.14));box-shadow:0 0 24px rgba(215,173,104,.12)}
    .ranked-menu-group:before{content:'COIN GAMES';font:700 10px/1 system-ui,sans-serif;letter-spacing:2px;color:#f2ce8b;text-align:center}
    .menu-secondary{background:rgba(28,19,14,.86);border:1px solid rgba(215,173,104,.36);color:#f5e7cc;cursor:pointer}
    .menu-ranked{background:linear-gradient(180deg,#b98a38,#80551e);border:1px solid #f0cc7b;color:#fff7df;cursor:pointer;box-shadow:inset 0 1px rgba(255,255,255,.22),0 8px 20px rgba(0,0,0,.28)}
    .menu-ranked:hover,.menu-ranked:focus-visible{filter:brightness(1.08)}
    .account-menu-box{position:absolute;right:clamp(12px,3vw,32px);top:clamp(12px,3vw,28px);width:min(285px,40vw);padding:12px 14px;border:1px solid rgba(215,173,104,.52);border-radius:13px;background:rgba(18,12,8,.91);box-shadow:0 10px 28px rgba(0,0,0,.35);z-index:4;font-family:system-ui,sans-serif;text-align:left}
    .account-menu-box strong{display:block;font-size:15px;color:#fff}.account-menu-box .wallet{display:block;margin-top:3px;color:#f3cf81;font-weight:800}.account-menu-box p{font-size:11px;line-height:1.35;margin:0 0 9px;color:#d8c4a2}.account-menu-actions{display:flex;gap:6px;flex-wrap:wrap}.account-menu-actions button{font-size:11px;padding:6px 8px;border-radius:8px;border:1px solid rgba(215,173,104,.4);background:#3b2417;color:#fff;cursor:pointer}
    dialog.gostop-account-dialog::backdrop,dialog.gostop-request-dialog::backdrop{background:rgba(0,0,0,.72)}
    .account-dialog-card{width:min(440px,90vw);display:grid;gap:10px}.account-tabs{display:flex;gap:7px}.account-tabs button{flex:1}.account-form{display:grid;gap:8px}.account-form label{display:grid;gap:4px;font:600 12px/1.2 system-ui,sans-serif;color:#ead4af}.account-form input{width:100%;padding:11px 12px;border-radius:9px;border:1px solid rgba(215,173,104,.42);background:#130d09;color:#fff;font:15px system-ui,sans-serif}.account-error{min-height:18px;color:#ff9a86;font:12px system-ui,sans-serif}.account-help{color:#cbb894;font:11px/1.4 system-ui,sans-serif}
    .leaderboard-screen{position:fixed;inset:0;z-index:1900;background:radial-gradient(circle at 50% 15%,#52321f,#130c08 58%,#080503);display:grid;grid-template-rows:auto 1fr auto;gap:12px;padding:clamp(18px,4vw,42px);color:#f5e7cc}.leaderboard-screen[hidden]{display:none}.leaderboard-title{text-align:center}.leaderboard-title h1{margin:0;font-size:clamp(32px,6vw,64px)}.leaderboard-title p{margin:4px 0 0;color:#d3bb92}.leaderboard-table-wrap{overflow:auto;width:min(1050px,92vw);margin:auto;border:1px solid rgba(215,173,104,.36);border-radius:15px;background:rgba(22,14,9,.78)}.leaderboard-table{width:100%;border-collapse:collapse;font-family:system-ui,sans-serif}.leaderboard-table th,.leaderboard-table td{padding:11px 12px;border-bottom:1px solid rgba(215,173,104,.14);text-align:right;white-space:nowrap}.leaderboard-table th:nth-child(2),.leaderboard-table td:nth-child(2){text-align:left}.leaderboard-table th{position:sticky;top:0;background:#29190f;color:#f3ce89}.leaderboard-provisional{opacity:.62}.leaderboard-provisional td:first-child:after{content:' P';font-size:9px;color:#e7c47c}.leaderboard-nav{position:absolute;top:50%;transform:translateY(-50%);width:48px;height:64px;border:1px solid rgba(215,173,104,.45);border-radius:12px;background:rgba(30,18,11,.75);color:#fff;font-size:30px;cursor:pointer}.leaderboard-prev{left:12px}.leaderboard-next{right:12px}.leaderboard-return{justify-self:center;min-width:180px;padding:11px 22px;border-radius:11px;border:1px solid #d7ad68;background:#43281a;color:#fff;font-weight:800;cursor:pointer}.leaderboard-attract-note{text-align:center;font:11px system-ui,sans-serif;color:#9f8a6b}
    .online-lobby-panel{position:fixed;inset:0;z-index:1850;background:rgba(10,7,5,.93);display:grid;place-items:center;padding:18px;overflow:auto}.online-lobby-panel[hidden]{display:none}.online-lobby-card{width:min(760px,94vw);max-height:92vh;overflow:auto;background:#1d130d;border:1px solid rgba(215,173,104,.4);border-radius:17px;padding:20px;box-shadow:0 22px 60px rgba(0,0,0,.55)}.online-lobby-card h2{margin-top:0}.online-method{padding:14px 0;border-top:1px solid rgba(215,173,104,.18)}.online-method:first-of-type{border-top:0}.online-search-row{display:flex;gap:7px}.online-search-row input{flex:1;min-width:0;padding:10px;border-radius:9px;border:1px solid rgba(215,173,104,.35);background:#0e0907;color:#fff}.online-search-row button,.online-lobby-actions button,.online-player-row{border:1px solid rgba(215,173,104,.38);background:#3b2417;color:#fff;border-radius:9px;padding:9px 11px;cursor:pointer}.online-player-list{display:grid;gap:7px;margin-top:9px}.online-player-row{display:grid;grid-template-columns:minmax(120px,1fr) repeat(3,auto);gap:12px;align-items:center;text-align:left}.online-player-row small{color:#bda782}.online-player-row strong{overflow:hidden;text-overflow:ellipsis}.online-lobby-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:12px}.online-existing-controls{display:grid;gap:9px}.online-existing-controls .online-join-form{display:grid!important}.lobby-status{min-height:18px;font:12px system-ui,sans-serif;color:#d9c49f}
    .gostop-request-dialog .dialog-card{max-width:420px;text-align:center}.request-player-stats{font:12px/1.5 system-ui,sans-serif;color:#d7c09a}
    @media(max-width:700px){.account-menu-box{position:relative;right:auto;top:auto;width:min(520px,92vw);margin:10px auto 0}.solo-start-overlay{align-content:start!important}.gostop-main-menu{margin-top:12px}.online-player-row{grid-template-columns:1fr 1fr;gap:5px}.leaderboard-nav{width:38px;height:54px}.leaderboard-table th,.leaderboard-table td{padding:9px 7px;font-size:12px}}
  `;document.head.appendChild(style);

  const overlay=$('soloStartOverlay'),playPractice=$('playSoloBtn'),createRoom=$('createOnlineBtn'),joinForm=$('joinOnlineForm'),howTo=$('howToBtn'),onlineStatus=$('onlineStatus');
  if(!overlay||!playPractice)return;

  playPractice.textContent='Practice Game';playPractice.className='menu-secondary';
  const accountBox=document.createElement('aside');accountBox.id='accountMenuBox';accountBox.className='account-menu-box';overlay.appendChild(accountBox);
  const menu=document.createElement('div');menu.className='gostop-main-menu';
  const rankedGroup=document.createElement('div');rankedGroup.className='ranked-menu-group';
  const rankedSolo=document.createElement('button');rankedSolo.type='button';rankedSolo.className='menu-ranked';rankedSolo.textContent='Solo Play';rankedSolo.id='rankedSoloBtn';
  const onlinePlay=document.createElement('button');onlinePlay.type='button';onlinePlay.className='menu-ranked';onlinePlay.textContent='Online Play';onlinePlay.id='onlinePlayMenuBtn';
  const leaderboardBtn=document.createElement('button');leaderboardBtn.type='button';leaderboardBtn.className='menu-secondary';leaderboardBtn.textContent='Global Leaderboard';leaderboardBtn.id='leaderboardMenuBtn';
  if(howTo){howTo.className='menu-secondary';howTo.textContent='How to Play';}
  rankedGroup.append(rankedSolo,onlinePlay);menu.append(playPractice,rankedGroup,leaderboardBtn);if(howTo)menu.append(howTo);overlay.appendChild(menu);

  // Preserve existing room-code controls but move them into the Online Play panel.
  const onlinePanel=document.createElement('section');onlinePanel.id='onlineLobbyPanel';onlinePanel.className='online-lobby-panel';onlinePanel.hidden=true;onlinePanel.innerHTML=`<div class="online-lobby-card"><h2>Online Play</h2><div class="online-method"><strong>Invite by Email</strong><p class="account-help">Enter a friend's email. Email delivery will use the signed GoStop invite service when configured.</p><div class="online-search-row"><input id="onlineInviteEmail" type="email" autocomplete="email" placeholder="friend@example.com"><button id="onlineInviteEmailBtn" type="button">Send Invite</button></div></div><div class="online-method"><strong>Find an Online Player</strong><p class="account-help">Search by nickname or choose one of the five online players closest to you by Score, Games Played, and Wallet Coins.</p><div class="online-search-row"><input id="onlineNicknameSearch" autocomplete="off" placeholder="Nickname"><button id="onlineNicknameSearchBtn" type="button">Search</button></div><div id="recommendedPlayers" class="online-player-list"></div></div><div class="online-method"><strong>Room Code / Share Link</strong><div id="onlineExistingControls" class="online-existing-controls"></div></div><p id="lobbyStatus" class="lobby-status" role="status"></p><div class="online-lobby-actions"><button id="onlineLobbyClose" type="button">Return</button></div></div>`;
  document.body.appendChild(onlinePanel);const controls=$('onlineExistingControls');if(createRoom){createRoom.textContent='Create Room / Share Code';controls.appendChild(createRoom);}if(joinForm)controls.appendChild(joinForm);if(onlineStatus)controls.appendChild(onlineStatus);

  const authDialog=document.createElement('dialog');authDialog.id='accountDialog';authDialog.className='gostop-account-dialog';authDialog.innerHTML=`<div class="dialog-card account-dialog-card"><button class="dialog-close" id="accountDialogClose" type="button" aria-label="Close">×</button><h2 id="accountDialogTitle">Log In</h2><div class="account-tabs"><button id="loginTab" class="glass-btn strong" type="button">Log In</button><button id="registerTab" class="glass-btn" type="button">Create ID</button></div><form id="loginForm" class="account-form"><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="go-btn" type="submit">Log In</button></form><form id="registerForm" class="account-form" hidden><label>Email<input name="email" type="email" autocomplete="email" required></label><label>Nickname<input name="nickname" autocomplete="nickname" maxlength="16" required></label><label>Password<input name="password" type="password" autocomplete="new-password" required></label><label>Confirm Password<input name="confirmPassword" type="password" autocomplete="new-password" required></label><p class="account-help">Use at least 8 characters. Common passwords such as 12345 or qwerty are not accepted.</p><button class="go-btn" type="submit">Register</button></form><p id="accountError" class="account-error" role="alert"></p></div>`;document.body.appendChild(authDialog);
  const successDialog=document.createElement('dialog');successDialog.className='gostop-account-dialog';successDialog.innerHTML=`<div class="dialog-card account-dialog-card"><h2>Account Successfully Registered</h2><p>You received 100 signup Coins and today's 100 daily Coins.</p><button id="registrationOk" class="go-btn" type="button">OK</button></div>`;document.body.appendChild(successDialog);
  const requestDialog=document.createElement('dialog');requestDialog.className='gostop-request-dialog';requestDialog.innerHTML=`<div class="dialog-card"><h2>Online Play Request</h2><p id="requestPlayerName"></p><p id="requestPlayerStats" class="request-player-stats"></p><div class="decision-actions"><button id="requestAccept" class="go-btn" type="button">Accept</button><button id="requestDecline" class="stop-btn" type="button">Decline</button></div></div>`;document.body.appendChild(requestDialog);let pendingRequest=null;

  const leaderboard=document.createElement('section');leaderboard.id='leaderboardScreen';leaderboard.className='leaderboard-screen';leaderboard.hidden=true;leaderboard.innerHTML=`<header class="leaderboard-title"><h1 id="leaderboardHeading">Global Leaderboard</h1><p id="leaderboardSubtitle"></p></header><button class="leaderboard-nav leaderboard-prev" id="leaderboardPrev" type="button" aria-label="Previous leaderboard">‹</button><div class="leaderboard-table-wrap"><table class="leaderboard-table"><thead><tr><th>Rank</th><th>Nickname</th><th>Score</th><th>Total Coins</th><th>Games Played</th></tr></thead><tbody id="leaderboardRows"></tbody></table></div><button class="leaderboard-nav leaderboard-next" id="leaderboardNext" type="button" aria-label="Next leaderboard">›</button><div><p id="leaderboardAttractNote" class="leaderboard-attract-note"></p><button class="leaderboard-return" id="leaderboardReturn" type="button">Return</button></div>`;document.body.appendChild(leaderboard);

  function renderAccountBox(){
    if(account){const place=[account.regionCode,account.countryCode].filter(Boolean).join(', ');accountBox.innerHTML=`<strong>${flagEmoji(account.countryCode)} ${escapeHtml(account.nickname)}</strong><span class="wallet">🪙 ${Number(account.walletCoins)||0} Coins</span>${place?`<p>${escapeHtml(place)}</p>`:''}<div class="account-menu-actions"><button id="accountLogout" type="button">Log Out</button></div>`;$('accountLogout')?.addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'});}catch(_){}clearSession();});}
    else{accountBox.innerHTML=`<p><strong>Create an ID</strong> to play with friends, earn Coins, and compete in the global leaderboard.</p><div class="account-menu-actions"><button id="accountCreate" type="button">Create ID</button><button id="accountLogin" type="button">Log In</button></div>`;$('accountCreate')?.addEventListener('click',()=>showAuth('register'));$('accountLogin')?.addEventListener('click',()=>showAuth('login'));}
  }
  function showAuth(mode='login'){const registering=mode==='register';$('loginForm').hidden=registering;$('registerForm').hidden=!registering;$('accountDialogTitle').textContent=registering?'Create ID':'Log In';$('loginTab').classList.toggle('strong',!registering);$('registerTab').classList.toggle('strong',registering);$('accountError').textContent='';if(!authDialog.open)authDialog.showModal();pauseAttract();}
  function requireAuth(mode='login'){if(account)return Promise.resolve(account);showAuth(mode);return new Promise(resolve=>authWaiters.push(resolve));}
  $('loginTab').addEventListener('click',()=>showAuth('login'));$('registerTab').addEventListener('click',()=>showAuth('register'));$('accountDialogClose').addEventListener('click',()=>authDialog.close());
  $('loginForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);$('accountError').textContent='';try{const data=await api('/api/auth/login',{method:'POST',auth:false,body:{email:form.get('email'),password:form.get('password')}});saveSession(data);authDialog.close();scheduleAttract();}catch(error){$('accountError').textContent=error.message;}});
  $('registerForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget),body=Object.fromEntries(form.entries());$('accountError').textContent='';if(Object.values(body).some(value=>!String(value).trim())){$('accountError').textContent='Please fill out all registration information.';return;}try{const data=await api('/api/auth/register',{method:'POST',auth:false,body});saveSession(data);authDialog.close();successDialog.showModal();}catch(error){$('accountError').textContent=error.message;}});
  $('registrationOk').addEventListener('click',()=>{successDialog.close();scheduleAttract();});

  function renderLeaderboardPage(){if(!leaderboardData)return;const monthly=leaderboardPage===1,rows=monthly?leaderboardData.monthly:leaderboardData.global;$('leaderboardHeading').textContent=monthly?'Monthly Leaderboard':'Global Leaderboard';$('leaderboardSubtitle').textContent=monthly?`${leaderboardData.month} · Ranked by average Coins won per game`:'All Time · Ranked by average Coins won per game';$('leaderboardRows').innerHTML=rows.map(row=>`<tr class="${row.provisional?'leaderboard-provisional':''}"><td>${row.rank}</td><td>${flagEmoji(row.countryCode)} ${escapeHtml(row.nickname)}${row.regionCode?` <small>${escapeHtml(row.regionCode)}</small>`:''}</td><td>${fmtScore(row.score)}</td><td>${Number(row.totalCoins)||0}</td><td>${Number(row.gamesPlayed)||0}</td></tr>`).join('')||'<tr><td colspan="5" style="text-align:center">No ranked games yet.</td></tr>';$('leaderboardAttractNote').textContent=attractMode?'Attract mode · touch/click anywhere to return to menu':`Players with fewer than ${leaderboardData.provisionalGames||10} games are provisional.`;}
  function rotateLeaderboard(){clearInterval(leaderboardTimer);leaderboardTimer=setInterval(()=>{leaderboardPage=leaderboardPage?0:1;renderLeaderboardPage();},5000);}
  async function showLeaderboard({attract=false}={}){try{leaderboardData=await api('/api/leaderboards',{auth:false});}catch(error){leaderboardData={global:[],monthly:[],month:'',provisionalGames:10};$('leaderboardSubtitle').textContent=error.message;}attractMode=attract;leaderboardPage=0;leaderboard.hidden=false;$('leaderboardReturn').hidden=attract;renderLeaderboardPage();rotateLeaderboard();pauseAttract();}
  function hideLeaderboard(){leaderboard.hidden=true;attractMode=false;clearInterval(leaderboardTimer);leaderboardTimer=null;scheduleAttract();}
  function switchLeaderboard(delta=1){leaderboardPage=(leaderboardPage+delta+2)%2;renderLeaderboardPage();rotateLeaderboard();}
  $('leaderboardPrev').addEventListener('click',event=>{event.stopPropagation();switchLeaderboard(-1);});$('leaderboardNext').addEventListener('click',event=>{event.stopPropagation();switchLeaderboard(1);});$('leaderboardReturn').addEventListener('click',event=>{event.stopPropagation();hideLeaderboard();});leaderboard.addEventListener('click',event=>{if(event.target.closest('button'))return;if(attractMode)hideLeaderboard();else switchLeaderboard(1);});leaderboardBtn.addEventListener('click',()=>showLeaderboard());

  function pauseAttract(){clearTimeout(attractTimer);attractTimer=null;}
  function scheduleAttract(){pauseAttract();if(overlay.hidden||authDialog.open||successDialog.open||!onlinePanel.hidden||!leaderboard.hidden)return;attractTimer=setTimeout(()=>{if(!overlay.hidden&&!authDialog.open&&onlinePanel.hidden)showLeaderboard({attract:true});},10000);}
  ['pointerdown','keydown','touchstart'].forEach(type=>overlay.addEventListener(type,scheduleAttract,{passive:true}));new MutationObserver(scheduleAttract).observe(overlay,{attributes:true,attributeFilter:['hidden']});

  function closeLobby(){if(lobbySocket){try{lobbySocket.close();}catch(_){}lobbySocket=null;}onlinePanel.hidden=true;pendingRequest=null;if(requestDialog.open)requestDialog.close();scheduleAttract();}
  function playerRow(player){const button=document.createElement('button');button.type='button';button.className='online-player-row';button.innerHTML=`<strong>${flagEmoji(player.countryCode)} ${escapeHtml(player.nickname)}${player.regionCode?` <small>${escapeHtml(player.regionCode)}</small>`:''}</strong><span><small>Score</small><br>${fmtScore(player.score)}</span><span><small>Games</small><br>${Number(player.gamesPlayed)||0}</span><span><small>Wallet</small><br>🪙 ${Number(player.walletCoins)||0}</span>`;button.addEventListener('click',()=>{if(lobbySocket?.readyState===WebSocket.OPEN){lobbySocket.send(JSON.stringify({type:'challenge',accountId:player.accountId}));$('lobbyStatus').textContent=`Play request sent to ${player.nickname}…`;}});return button;}
  function showPlayers(players,label='Recommended online players'){const root=$('recommendedPlayers');root.replaceChildren();const title=document.createElement('small');title.textContent=label;root.appendChild(title);if(!players?.length){const empty=document.createElement('p');empty.className='account-help';empty.textContent='No matching available players are online right now.';root.appendChild(empty);return;}players.forEach(player=>root.appendChild(playerRow(player)));}
  function connectLobby(){if(lobbySocket?.readyState===WebSocket.OPEN)return;const url=new URL(apiUrl('/api/lobby/ws'),location.href);url.protocol=url.protocol==='https:'?'wss:':'ws:';lobbySocket=new WebSocket(url,`gostop-auth.${authToken}`);lobbySocket.onopen=()=>{$('lobbyStatus').textContent='Online lobby connected.';};lobbySocket.onclose=()=>{$('lobbyStatus').textContent='Online lobby disconnected.';lobbySocket=null;};lobbySocket.onerror=()=>{$('lobbyStatus').textContent='Could not connect to the online lobby.';};lobbySocket.onmessage=async event=>{let message;try{message=JSON.parse(event.data);}catch(_){return;}if(message.type==='recommendations')showPlayers(message.players);else if(message.type==='searchResults')showPlayers(message.players,`Search results for “${message.query}”`);else if(message.type==='challengeSent')$('lobbyStatus').textContent=`Waiting for ${message.to.nickname} to respond…`;else if(message.type==='challengeDeclined')$('lobbyStatus').textContent=`${message.by.nickname} declined the request.`;else if(message.type==='challengeError'||message.type==='challengeCancelled')$('lobbyStatus').textContent=message.message||'Play request could not be completed.';else if(message.type==='playRequest'){pendingRequest=message;$('requestPlayerName').textContent=`${flagEmoji(message.from.countryCode)} ${message.from.nickname} wants to play GoStop with you.`;$('requestPlayerStats').textContent=`Score ${fmtScore(message.from.score)} · ${message.from.gamesPlayed} games · 🪙 ${message.from.walletCoins} Coins`;requestDialog.showModal();try{navigator.vibrate?.([180,80,180]);}catch(_){}}else if(message.type==='challengeAccepted'){pendingRequest=null;if(requestDialog.open)requestDialog.close();onlinePanel.hidden=true;try{lobbySocket?.send(JSON.stringify({type:'setAvailability',available:false}));}catch(_){};if(typeof globalThis.GoStopBeginOnlineRoom==='function')await globalThis.GoStopBeginOnlineRoom(message.room);else globalThis.dispatchEvent(new CustomEvent('gostop-ranked-room-ready',{detail:{room:message.room}}));}};}
  $('onlineNicknameSearchBtn').addEventListener('click',()=>{const query=$('onlineNicknameSearch').value.trim();if(lobbySocket?.readyState===WebSocket.OPEN)lobbySocket.send(JSON.stringify(query?{type:'search',query}:{type:'recommendations'}));});$('onlineNicknameSearch').addEventListener('keydown',event=>{if(event.key==='Enter'){$('onlineNicknameSearchBtn').click();}});
  $('requestAccept').addEventListener('click',()=>{if(pendingRequest&&lobbySocket?.readyState===WebSocket.OPEN)lobbySocket.send(JSON.stringify({type:'challengeResponse',requestId:pendingRequest.requestId,accept:true}));requestDialog.close();});$('requestDecline').addEventListener('click',()=>{if(pendingRequest&&lobbySocket?.readyState===WebSocket.OPEN)lobbySocket.send(JSON.stringify({type:'challengeResponse',requestId:pendingRequest.requestId,accept:false}));pendingRequest=null;requestDialog.close();});
  $('onlineLobbyClose').addEventListener('click',closeLobby);onlinePlay.addEventListener('click',async()=>{await requireAuth();onlinePanel.hidden=false;pauseAttract();connectLobby();});
  $('onlineInviteEmailBtn').addEventListener('click',()=>{$('lobbyStatus').textContent='Email invitations are ready for the signed-invite service; outbound email delivery still needs the mail provider configured.';});
  rankedSolo.addEventListener('click',async()=>{await requireAuth();globalThis.dispatchEvent(new CustomEvent('gostop-ranked-solo-request',{detail:{account:getAccount()}}));});

  globalThis.GoStopRanked=Object.freeze({getAuthToken,getAccount,refreshAccount,requireAuth,updateFromSnapshot,showLeaderboard,flagEmoji});
  renderAccountBox();refreshAccount().finally(scheduleAttract);
})();
